/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.esm;

import com.epam.esm.entity.GiftSertificate;
import com.epam.esm.service.GiftService;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.util.List;

public class Library {

    private GiftService service;

    public  void startApplication() {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.scan("com.epam.esm");
        context.refresh();
        this.service=context.getBean(GiftService.class);
    }

    public void save(GiftSertificate certificate) {
        service.save(certificate);
    }

    public GiftSertificate getById(Integer id) {
        return service.getById(id);
    }

    public List<GiftSertificate> getAll() {
        return service.getAll();
    }
    public boolean delete(Integer id) {
        return service.delete(id);
    }

    public GiftSertificate update(Integer id,GiftSertificate newObj) {
        return service.update(id,newObj);
    }
}
